name: nemo
channels:
  - nvidia/label/cuda-11.8.0
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  - python=3.10.12
  - pip
  - pytorch=2.2.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - cuda-toolkit
  - libsndfile
  - ffmpeg
  - Cython
  - packaging
  - typing_extensions>=4.5
  - cuda-nvcc
  - git
  - swig
  - boost=1.80.0
  - cmake>=3.1
  - pip:
    - nemo_toolkit[all]